sudo: required
services:
  - docker
script:
  - docker build -t abhishekgupta86/travis_ci .
  - docker images abhishekgupta86/travis_ci
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: main